### PR TITLE
Destroy vectors with elements

### LINKED ISSUE #333: [Bug] stdlib bcs tests encode_128 and encode_129 break on non-empty vector destroying
# 🐛 Bug

Move native run-time doesn't currently handle destroying vectors with elements (only empty vectors can be destroyed).
The tests encode_128, and encode_129 depend on being able to destroy non-empty vectors at the end of the test functions.
encode_129 is expected_failure test. It passes because the test doesn't check the abort code, but it aborts for a different reason.

## To reproduce

Run encode_128 and encode_129 tests

**Code snippet to reproduce**
```
cargo run -p move-cli --features solana-backend --bin move -- test --solana -p language/move-stdlib encode_129
```

**Stack trace/error message**
```
event 0: "panicked at 'assertion failed: `(left == right)`\n  left: `0`,\n right: `1`: can't destroy vectors with elements yet', language/move-native/src/rt.rs:17:5"
event 1: "0x65, 0x65, 0x65, 0x65, 0x65"
[DEBUG language/solana/move-to-solana/src/runner.rs:359] Solana VM abort with code 101
[ PASS    ] 0x1::bcs_tests::encode_129

Test Statistics:

┌────────────────────────────┬────────────┬───────────────────────────┐
│         Test Name          │    Time    │         Gas Used          │
├────────────────────────────┼────────────┼───────────────────────────┤
│ 0x1::bcs_tests::encode_129 │   0.002    │           10949           │
└────────────────────────────┴────────────┴───────────────────────────┘

Test result: OK. Total tests: 1; passed: 1; failed: 0

```

## Expected Behavior

Test passes but because its execution reached the limit of max_call_depth.

The test encode_128 should pass without expected failure.

### PR DESCRIPTION
**Pull request by brson**
This implements the vec_destroy runtime call for vectors with elements, including other vectors and structs.

This patch makes the encode_128 test pass, as described in https://github.com/solana-labs/move/issues/333, but it causes encode_129 to fail (because move-native serializes a deeply nested type that should instead produce a recursion-limit error). I filed https://github.com/solana-labs/move/issues/367 about encode_129.

Fixes https://github.com/solana-labs/move/issues/333

### CODE REVIEW

**Review by dmakarov — APPROVED** [review]
Thank you!

**Review by ksolana — APPROVED** [review]

File: language/move-native/src/vector.rs [hunk 1]
```diff
@@ -203,8 +203,21 @@ impl MoveUntypedVector {
...
     pub unsafe fn destroy_empty(self, type_ve: &MoveType) {
+        assert_eq!(self.length, 0);
+        self.destroy(type_ve);
+    }
+
+    /// # Safety
+    ///
+    /// Unsafe because the provided type must be correct.
+    //
+    // todo: We should probably just leak the vector instead of
```
Comment (ksolana) [inline language/move-native/src/vector.rs:214]: can we add a flag that will help switch between leak vs. drop. that'd be easier to test i guess. maybe as a separate patch if you think this is a good idea.

**Comment by ksolana** [comment]
!help

File: language/move-native/src/vector.rs (hunk 1 above)
Comment (brson) [reply language/move-native/src/vector.rs:214]: Yeah we can do that separately.
