### PR TITLE
Fix defects: TargetMachine created too late and DataLayout incorrect.

### LINKED ISSUE #198: TargetMachine created too late; incorrect data layout.
The main driver sets up the `TargetMachine` and `DataLayout` at the very end of compilation-- _after_ the `Module` has been created and translated. This means that the default `DataLayout` will be in effect during translation-- not the `SBF` data layout. 

One resulting problem is that, e.g., structure alignment information is incorrectly reported by LLVM. The default DL is under-aligned with respect to SBF alignment requirements in cases-- e.g., a 64-bit integer is only 4-byte aligned in the default DL. Previously, I worked around this defect in the rtty work by hard coding the SBF DL.

Secondly, the target triple and data layout are never set on the `Module` when we output either textual or bitcode LLVM IR for the module.

This issue is a reminder to rework the target machine and layouts initialization and setup. That will remedy the defect and is also LLVM idiomatic.

### PR DESCRIPTION
**Pull request by nvjle**
This patch fixes the two defects in:
https://github.com/solana-labs/move/issues/198.

To summarize: Previously the TargetMachine was created too late so that the incorrect DataLayout was in effect during translation (resulting in incorrect alignments, etc). The TargetMachine is now created before translation and the data layout is set upon module processing.

Secondly, the target triple and data layout specifiers previously were never set on the Module when outputting either textual or bitcode LLVM IR for the module.

This patch also fixes all the "unsafe leakage" from module llvm. This really is an orthogonal set of changes and should be a separate patch, however, the custom clippy insisted I do this now. Wrap up all LLVM references such as LLVMValueRef and so forth into structs, and reference only those within the translator.

Test results were remastered (eyeball checked for correctness). The changes are of two kinds (due to the fixes):
1. All LLVM IR expected result files now contain the expected "target datalayout" and "target triple" specifiers.
2. Various alignment specifiers on loads and stores increased (e.g., 4 to 8). This is as expected and the values were previously incorrectly under-aligned.

### CODE REVIEW

**Review by ksolana — APPROVED** [review]
~Too big to review in depth~ but goals of the patch LGTM 

Just reviewed it, thanks for fixing!

File: language/tools/move-mv-llvm-compiler/src/stackless/translate.rs [hunk 1]
```diff
@@ -187,14 +191,17 @@ pub struct ModuleContext<'mm, 'up> {
...
+    target_machine: &'up TargetMachine,
     args: &'up Args,
 }
 
 impl<'mm, 'up> ModuleContext<'mm, 'up> {
     pub fn translate(mut self) -> llvm::Module {
         let filename = self.env.get_source_path().to_str().expect("utf-8");
         self.llvm_module.set_source_file_name(filename);
+        self.llvm_module.set_target(self.target.triple());
+        self.llvm_module.set_data_layout(self.target_machine);
```
Comment (ksolana) [inline language/tools/move-mv-llvm-compiler/src/stackless/translate.rs:204]: Thanks for fixing this, we missed this in the beginning.

**Comment by ksolana** [comment]
rerunning the ci tests as the previous instance failed for some unknown reason.

**Comment by nvjle** [comment]
> ~Too big to review in depth~ but goals of the patch LGTM
> 
> Just reviewed it, thanks for fixing!

Thanks for reviewing. 
I'm not sure whether to commit now or wait for an answer on the CI issue above (I asked in the Discord if anyone knows how to solve it). This looks like a problem on the github/CI end of things in the `Run ./.github/actions/acquire-solana-tools` step.

**Comment by ksolana** [comment]
okay to wait if this is not too urgent to land.
